/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkbenchIndexRouteImport } from './routes/workbench.index'
import { Route as WorkbenchIdRouteImport } from './routes/workbench.$id'

const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkbenchIndexRoute = WorkbenchIndexRouteImport.update({
  id: '/workbench/',
  path: '/workbench/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkbenchIdRoute = WorkbenchIdRouteImport.update({
  id: '/workbench/$id',
  path: '/workbench/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/developers': typeof DevelopersRoute
  '/workbench/$id': typeof WorkbenchIdRoute
  '/workbench/': typeof WorkbenchIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/developers': typeof DevelopersRoute
  '/workbench/$id': typeof WorkbenchIdRoute
  '/workbench': typeof WorkbenchIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/developers': typeof DevelopersRoute
  '/workbench/$id': typeof WorkbenchIdRoute
  '/workbench/': typeof WorkbenchIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/developers' | '/workbench/$id' | '/workbench/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/developers' | '/workbench/$id' | '/workbench'
  id: '__root__' | '/' | '/developers' | '/workbench/$id' | '/workbench/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevelopersRoute: typeof DevelopersRoute
  WorkbenchIdRoute: typeof WorkbenchIdRoute
  WorkbenchIndexRoute: typeof WorkbenchIndexRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workbench/': {
      id: '/workbench/'
      path: '/workbench'
      fullPath: '/workbench/'
      preLoaderRoute: typeof WorkbenchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workbench/$id': {
      id: '/workbench/$id'
      path: '/workbench/$id'
      fullPath: '/workbench/$id'
      preLoaderRoute: typeof WorkbenchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevelopersRoute: DevelopersRoute,
  WorkbenchIdRoute: WorkbenchIdRoute,
  WorkbenchIndexRoute: WorkbenchIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
